import { QueryInterface, DataTypes } from 'sequelize';

export async function up(queryInterface: QueryInterface): Promise<void> {
  await queryInterface.createTable('employee_base', {
    emp_id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    name: { type: DataTypes.STRING, allowNull: false },
    nationality: { type: DataTypes.STRING, allowNull: true },
    religion: { type: DataTypes.STRING, allowNull: true },
    dob: { type: DataTypes.DATE, allowNull: true },
    joining_date: { type: DataTypes.DATE, allowNull: true },
    age: { type: DataTypes.INTEGER, allowNull: true },
    contact_number: { type: DataTypes.STRING, allowNull: true },
    emp_photo: { type: DataTypes.STRING, allowNull: true },
    benefits: { type: DataTypes.STRING, allowNull: true },
    iban: { type: DataTypes.STRING, allowNull: true },
    vacation_date: { type: DataTypes.DATE, allowNull: true },
    notes: { type: DataTypes.STRING, allowNull: true },
    iqama_no: { type: DataTypes.BIGINT, allowNull: true },
    iqama_expiry_date: { type: DataTypes.DATE, allowNull: true },
    iqama_profession: { type: DataTypes.STRING, allowNull: true },
    iqama: { type: DataTypes.STRING, allowNull: true },
    passport_number: { type: DataTypes.STRING, allowNull: true },
    passport_expiry_date: { type: DataTypes.DATE, allowNull: true },
    passport: { type: DataTypes.STRING, allowNull: true },
    passport_2: { type: DataTypes.STRING, allowNull: true },
    ajeer: { type: DataTypes.STRING, allowNull: true },
    ajeer_expiration_date: { type: DataTypes.DATE, allowNull: true },
    insurance_card: { type: DataTypes.STRING, allowNull: true },
    insurance_card_expirationDate: { type: DataTypes.DATE, allowNull: true },
    vendor: { type: DataTypes.INTEGER, allowNull: true },
    salary_rate: { type: DataTypes.STRING, allowNull: true },
    client: { type: DataTypes.STRING, allowNull: true },
    client_location: { type: DataTypes.STRING, allowNull: true },
    staging_client: { type: DataTypes.STRING, allowNull: true },
    status: { type: DataTypes.STRING, allowNull: true },
    accommodation: { type: DataTypes.INTEGER, allowNull: true },
    contract_start: { type: DataTypes.DATE, allowNull: true },
    project_stop_date: { type: DataTypes.DATE, allowNull: true },
    lang_eng: { type: DataTypes.INTEGER, allowNull: true },
    lang_ar: { type: DataTypes.INTEGER, allowNull: true },
    lang_hind: { type: DataTypes.INTEGER, allowNull: true },
    appearance_presentable: { type: DataTypes.INTEGER, allowNull: true },
    apprearance_beard: { type: DataTypes.INTEGER, allowNull: true },
    skills: { type: DataTypes.STRING, allowNull: true },
    misconduct: { type: DataTypes.STRING, allowNull: true },
    rating: { type: DataTypes.INTEGER, allowNull: true },
    created_by: { type: DataTypes.STRING, allowNull: true },
    updated_by: { type: DataTypes.STRING, allowNull: true },
    employee_type: { type: DataTypes.STRING, allowNull: true },
    position: { type: DataTypes.STRING, allowNull: true },
    contract_end: { type: DataTypes.DATE, allowNull: true },
    disconnection_date: { type: DataTypes.DATE, allowNull: true },
    disconnection_reason: { type: DataTypes.STRING, allowNull: true },
    file_number: { type: DataTypes.STRING, allowNull: true },
    bank_name: { type: DataTypes.STRING, allowNull: true },
    vendor_rate: { type: DataTypes.STRING, allowNull: true },
    monthly_other_allowance: { type: DataTypes.STRING, allowNull: true },
    monthly_transportation_allowance: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    monthly_housing_allowance: { type: DataTypes.STRING, allowNull: true },
    employee_contract_start: { type: DataTypes.DATE, allowNull: true },
    total_leaves: { type: DataTypes.INTEGER, allowNull: true },
  });
}

export async function down(queryInterface: QueryInterface): Promise<void> {
  await queryInterface.dropTable('employee_base');
}
